### ISSUE TITLE
接口列表无法展示全部选项

### ISSUE THREAD

**Issue by skyqty** [phobal/ivideo#11]
接口列表无法展示全部选项
window 和 macos 上都可重现

**Comment by phobal** [comment]
这个 bug 已经修复了，但是还没 release，最近家里网络不好，你可以 clone 下来自己 build 一下

**Comment by phobal** [comment]
@skyqty 这个 bug 的修复版本已发布，前往 [release](https://github.com/phobal/ivideo/releases/tag/1.1.1) 更新下载即可

**Comment by skyqty** [comment]
多谢
