### ISSUE TITLE
能否支持浏览器的切换？

### ISSUE THREAD

**Issue by ResolveWang** [phobal/ivideo#12]
首先感谢作者的奉献，试用了一下，感觉用起来确实比较方便。

我试用的环境是Linux，换到Mac上就不行了，一直提示没安装Flash，事实上是安装过的。能否可以做个设置，比如切换浏览器为safri

**Comment by pyyzcwg2833** [comment]
不可以的，Electron基于Chromium

**Comment by ResolveWang** [comment]
@pyyzcwg2833 好的，谢谢。请问有不有啥解决方案呢？
