### ISSUE TITLE
#win10安装的时候没有反应

### ISSUE THREAD

**Issue by Funwentao** [phobal/ivideo#15]
rt

**Comment by phobal** [comment]
你可以截个图么？或者你留下个邮件 我给你免安装包

**Comment by Funwentao** [comment]
就是点击了没有反应，2419584260@qq.com

**Comment by Funwentao** [comment]
不排除是电脑原因，到时答复

**Comment by phobal** [comment]
@Funwentao 你去[这里](https://github.com/phobal/ivideo/releases/tag/1.1.1)下载最新的版本，免安装包，解压后点击 `ivideo.exe` 就可以的
