### ISSUE TITLE
咨询笔者的一些简单问题！

### ISSUE THREAD

**Issue by xiaopeng520** [phobal/ivideo#23]
1. 笔者这些线路是你自己开发的吗？

2.笔者这些线路是你自己维护的吗？还是反馈别人维护？

3.如果是你全是你自己弄的，是否有意向交换？

**Comment by touch-head-optimistically** [comment]
are you fishing？

**Comment by phobal** [comment]
这些线路都是调用的第三方的，我不负责维护和管理，我只是“借”用他们的接口来学习，可能没有交换的价值
