### ISSUE TITLE
ivideo 没有32位版本

### ISSUE THREAD

**Issue by iwanfu** [phobal/ivideo#32]

**Comment by phobal** [comment]
windows 版本 32 和 64 位都支持的，只是目前不支持 windows xp

**Comment by sgrjyb** [comment]
![default](https://user-images.githubusercontent.com/28247198/42743589-e245393e-88f7-11e8-99be-180fed4c319d.PNG)

**Comment by phobal** [comment]
我身边没有 32 位的电脑，你自己把代码 clone 下来编译一下试试呢？就用 yarn package 这个命令




| |
冯博
web前端开发工程师
|
|
众安在线
邮箱：phobal@126.com
|

签名由 网易邮箱大师 定制

在2018年07月17日 17:45，soso8531337 写道：

我的是win7 32bit， 但是提示不兼容
