### ISSUE TITLE
star 越来越多,就问作者慌不慌,是不是要准备删仓库了

### ISSUE THREAD

**Issue by chuanshuo-yongyuan** [phobal/ivideo#38]
star 越来越多,就问作者慌不慌,是不是要准备删仓库了

**Comment by AdwardA** [comment]
连续两周上GitHub周报是最骚的

**Comment by alphardex** [comment]
没事，我还搞了个网页版的，作为一条后路吧:smile:

https://ivideo-python.herokuapp.com/

**Comment by bestK** [comment]
:unamused: 拜托，这只是个接口调用工具。

所有的解析接口我想都是作者在网上搜集的。

**Comment by alphardex** [comment]
楼上说的对，但是考虑到国内下载速度有点慢，就把接口直接放到网络上了

**Comment by ahz549467483** [comment]
> 没事，我还搞了个网页版的，作为一条后路吧😄
> 
> https://ivideo-python.herokuapp.com/

现在没用了，有新地址吗
