### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by sanchiqingfeng** [phobal/ivideo#40]
安装完了之后，选择站点还是看不了，有没有老铁可以用的，能不能指导一下

**Comment by bdtbbylzy** [comment]
【环境：Arch Linux】【Windows/Mac版本没用过，不知道，不过步骤应该都差不多】
运行主程序（electron-react-boilerplate）后，在左栏选择视频平台，右边选择要看的视频。如果需要vip或者无广告的话，在右上角选择线路中选5月21（试了几个，这个貌似能用），点击确定，然后跳转到解析接口，点击左下角的播放键就能看vip/无广告视频了。

**Comment by sanchiqingfeng** [comment]
@bdtbbylzy 回去试试5月21这个线路吧，试了大部分线路都是无效的

**Comment by bdtbbylzy** [comment]
@sanchiqingfeng 刚刚试了试，腾讯视频能用的是下面几个
1.万能接口5
2.【5月2】
3.【5月4】
4.【5月21】
5.【5月22】

不保证测试准确性，而且有的线路，第一次进不行，第二次进就能用了，你自己也可以多试试，我这里可能有不少漏掉的。

===
如果解决了问题，请记得close issue，保持版面整洁
