### ISSUE TITLE
下载不了啊

### ISSUE THREAD

**Issue by LUOCY028** [phobal/ivideo#41]

**Comment by fordtin** [comment]
我的开始也下载不了，下载一直失败，搞了好久才下载ok。现在我把这些都上传到百度网盘了，你可以看下：链接：https://pan.baidu.com/s/13vFZCBTckAnbSiEbhGBykQ 密码：gob7

**Comment by hanpanapn** [comment]
感谢

**Comment by phobal** [comment]
因为安装包是放在 github  上的，国内 GitHub 不是和稳定，你可以用代理上
