### ISSUE TITLE
【手机版】搞了个安卓手机版的

### ISSUE THREAD

**Issue by CrazyDudo** [phobal/ivideo#50]
https://github.com/CrazyDudo/fvip

**Comment by alphardex** [comment]
可以，这下[pc客户端](https://github.com/phobal/ivideo)、[网页版](https://github.com/alphardex/ivideo-python)、[app](https://github.com/CrazyDudo/fvip)三者都齐了:smirk:

**Comment by fordtin** [comment]
手机版本无法输入呀，安装好后，点击输入框，输入法弹不出来，手机型号：荣耀7i/ATH-AL00

**Comment by CrazyDudo** [comment]
@fordtin 已修复；）

**Comment by lai-bluejay** [comment]
> 可以，这下[pc客户端](https://github.com/phobal/ivideo)、[网页版](https://github.com/alphardex/ivideo-python)、[app](https://github.com/CrazyDudo/fvip)三者都齐了😏

网页版搭了个新的。主要线路资源不一样了
[网页版](http://lai7bluejay.leanapp.cn/)
