### ISSUE TITLE
全屏状态下画面显示有问题

### ISSUE THREAD

**Issue by CoolLby** [phobal/ivideo#56]
### 问题描述
- 全屏状态下视频画面会变蓝，十分怪异，窗口模式正常

###  问题截图
- 试过系统自带截图，qq截图等，截图一瞬间画面瞬间恢复正常，所以只能手机拍摄再与正常画面对比
  - 问题画面
    ![tim 20180721224926](https://user-images.githubusercontent.com/38807139/43036742-889d9566-8d39-11e8-9898-8d8d13464563.jpg)
    ![tim 20180721224912](https://user-images.githubusercontent.com/38807139/43036701-e8f29a16-8d38-11e8-9a49-5822bd52e1a7.jpg)
  - 正常画面
    ![2](https://user-images.githubusercontent.com/38807139/43036688-bf7aa9f8-8d38-11e8-8091-293ecb6a633a.png)
    ![default](https://user-images.githubusercontent.com/38807139/43036689-c0d84dd2-8d38-11e8-8ed9-90dc0d780af0.png)

### 运行环境
- 系统: Win10 X64 专业版
- PC: HP 735 G5 (笔记本)

**Comment by phobal** [comment]
这个可能跟你选择的线路有关系。你可以切换到其他可以使用的线路试试

**Comment by CoolLby** [comment]
@phobal 问题找到了，这个 hp735 g5的笔记本，在某些软件全屏时颜色会变成色盲模式。
