### ISSUE TITLE
yarn安装node依赖安装报错

### ISSUE THREAD

**Issue by SkyWongHZ** [phobal/ivideo#57]
按照readme文档在yarn安装依赖时候报错,截图如下所示,不知该如何解决?
[依赖安装报错](http://oo4wiq5wc.bkt.clouddn.com/2018-07-23_004010.png)

D:\electron\ivideo-master> yarn  install
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "win32" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/4] ⠂ waiting...
[2/4] ⠂ electron
[3/4] ⠂ node-sass
error D:\electron\ivideo-master\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: D:\electron\ivideo-master\node_modules\electron
Output:
D:\electron\ivideo-master\node_modules\electron\install.js:48
  throw err
  ^

Error: connect ETIMEDOUT 54.231.72.115:443
    at Object._errnoException (util.js:992:11)

**Comment by phobal** [comment]
看报错信息像是网络连接问题，你可以切换到国内源或者用梯子下载
