### ISSUE TITLE
不好使

### ISSUE THREAD

**Issue by sternapeg** [phobal/ivideo#68]
不好使，不知道这星星怎么这个高！

**Comment by wupeaking** [comment]
大家都是star之后等着以后尝试的。 结果发现好像不是很好用

**Comment by hanzichi** [comment]
不能用。。。官方给个说法啊。。

**Comment by phobal** [comment]
@all 这些视频接口的来源均来自网络，对于质量的好坏我也不好控制，目前线路也比较多，需要耐心尝试
