### ISSUE TITLE
本身就是侵权了

### ISSUE THREAD

**Issue by ZhYong10** [phobal/ivideo#7]
学习交流不是万能的借口。本身vip权限就应是限制使用的。

**Comment by elsagong** [comment]
没有这个，也会有其他破解vip的应用。。。

**Comment by ZhYong10** [comment]
别人盗版vip侵权不是你这样做的正当理由。

**Comment by dengnan123** [comment]
这样的轮子多了

**Comment by wenye123** [comment]
楼主！授人以鱼不如授人以渔，偷偷告诉我们怎么突破限制就行了！！

**Comment by vitacoding** [comment]
程序员的事儿，怎么能说是侵权呢，我们都很好学的。

**Comment by hanxu317317** [comment]
这也没有侵权啊. 只不过是一个工具. 视频地址是别的网站提供的.

**Comment by chenhonzhou** [comment]
这个实现实际上只是用了别人的接口，如作者所言，只做学习用途232333

**Comment by binlaniua** [comment]
真正高清的接口是不会放出来或者要认证的。。放出来的是供预览看看的AV画质

**Comment by ZhYong10** [comment]
@elsagong 试用了，很好用哈哈，所以请 close issue。

**Comment by willylee007** [comment]
这不就是把chrome插件做成客户端了吗。。

**Comment by Hypnoes** [comment]
不是没有盈利目的啊。

**Comment by elsagong** [comment]
@ZhYong10 这个问题不是我开的，应该要你自己关闭吧？
