### ISSUE TITLE
mac侧边栏只有爱奇艺

### ISSUE THREAD

**Issue by xdlkc** [phobal/ivideo#85]
<img width="1024" alt="machi 2019-01-04 14-01-12" src="https://user-images.githubusercontent.com/8935127/50675452-43e07d80-1029-11e9-933d-b75c2d02da8f.png">

**Comment by Freakwill** [comment]
昨天还好好的。

**Comment by phobal** [comment]
@xdlkc  @Freakwill 已解决，可以下载最新版体验 https://github.com/phobal/ivideo/releases/tag/v1.1.2

**Comment by Freakwill** [comment]
@phobal  我下载了最新版本，好像还是不行。ivideo/about 写的版本还是1.1.0，另外菜单选项`ivideo/about ElectronReact`是不是写错了。

**Comment by xdlkc** [comment]
> @xdlkc @Freakwill 已解决，可以下载最新版体验 https://github.com/phobal/ivideo/releases/tag/v1.1.2

可以了，感谢！

**Comment by phobal** [comment]
@Freakwill 版本号以 release 为准，`ivideo/about` 没及时更新
