### ISSUE TITLE
mac线路获取不到

### ISSUE THREAD

**Issue by heyanfeng** [phobal/ivideo#86]
且 侧边栏 只有爱奇艺
![2019-01-04 7 21 19](https://user-images.githubusercontent.com/15811017/50685962-59b86780-1056-11e9-81d9-4df12276783a.png)

**Comment by phobal** [comment]
@heyanfeng 已解决，可以下载最新版体验 https://github.com/phobal/ivideo/releases/tag/v1.1.2

**Comment by heyanfeng** [comment]
> @heyanfeng 已解决，可以下载最新版体验 https://github.com/phobal/ivideo/releases/tag/v1.1.2

ok了
