### ISSUE TITLE
yarn install出现错误

### ISSUE THREAD

**Issue by WTxiaomage** [phobal/ivideo#87]
$ yarn install
yarn install v1.12.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "win32" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error E:\ivideo\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\ivideo\node_modules\node-sass
Output:
Building: D:\nodejs\node.exe E:\ivideo\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\nodejs\\node.exe',
gyp verb cli   'E:\\ivideo\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.11.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\ivideo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\ivideo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\ivideo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\ivideo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\ivideo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\ivideo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\ivideo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\ivideo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\ivideo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\ivideo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\ivideo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\ivideo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (E:\\ivideo\\node_modules\\which\\which.js:13:12)\n    at F (E:\\ivideo\\node_modules\\which\\which.js:68:19)\n    at E (E:\\ivideo\\node_modules\\which\\which.js:80:29)\n    at E:\\ivideo\\node_modules\\which\\which.js:89:16\n    at E:\\ivideo\\node_modules\\isexe\\index.js:42:5\n    at E:\\ivideo\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\ivideo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\ivideo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\ivideo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\ivideo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\ivideo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\ivideo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\ivideo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\ivideo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\ivideo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\ivideo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\ivideo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\ivideo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (E:\\ivideo\\node_modules\\which\\which.js:13:12)\n    at F (E:\\ivideo\\node_modules\\which\\which.js:68:19)\n    at E (E:\\ivideo\\node_modules\\which\\which.js:80:29)\n    at E:\\ivideo\\node_modules\\which\\which.js:89:16\n    at E:\\ivideo\\node_modules\\isexe\\index.js:42:5\n    at E:\\ivideo\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\ivideo\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\ivideo\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\ivideo\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\nodejs\\node.exe" "E:\\ivideo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\ivideo\node_modules\node-sass
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by phobal** [comment]
@WTxiaomage 你的问题，node-sass 包很大，国内的网很难下载，你可以尝试挂代理下载
