### ISSUE TITLE
v1.1.2 win install error

### ISSUE THREAD

**Issue by LLcat1217** [phobal/ivideo#88]
A JavaScript error occurred in the main process
Error: Failed to get 'pepperFlashSystemPlugin' path at Object../app/main.dev.js

**Comment by phobal** [comment]
yarn install 一下试试

**Comment by TheTrueMan** [comment]
WIN10家庭版的不行，专业版就没问题。

**Comment by phobal** [comment]
@windht can you see it about flash plugin? I don't have win system

**Comment by phobal** [comment]
已修复，下载最新版体验 https://github.com/phobal/ivideo/releases/download/v1.1.3/ivideo-1.1.3-win.zip

**Comment by windht** [comment]
非常抱歉！我没想到在某些Win平台Electron自己的API会出现这种Blocking的错误。初步估计是win自身为64bit，电脑没安装flash或flash是32bit。
我弄了一个新的PR，用try catch的方法来跑append，这样一些可以正常加载flash的windows可以通过，并且之后也可以在catch中针对错误给用户提示（flash无法获取之类的）。
https://github.com/phobal/ivideo/pull/90
