### ISSUE TITLE
ivideo-1.1.2-win.zip安装后打开报错

### ISSUE THREAD

**Issue by michaelGitHub123** [phobal/ivideo#89]
windows7专业版，安装打开报错：A JavaScript error occurred in the main process，这个怎么解决？
![1](https://user-images.githubusercontent.com/46561807/50965509-186c0000-150d-11e9-9204-998cb9a35c42.png)

**Comment by jiqing112** [comment]
我也是这个错误。我是win10.一模一样的错误

**Comment by xiaojiaoup** [comment]
我也是这样，我还以为只有我有这个问题

**Comment by phobal** [comment]
@michaelGitHub123 @jiqing112 @xiaojiaoup 该问题已修复

https://github.com/phobal/ivideo/releases/download/v1.1.3/ivideo-1.1.3-win.zip

**Comment by michaelGitHub123** [comment]
已下载，能打开了
